### ISSUE TITLE
MainMenu.strings, Localizable.strings need to be updated

### ISSUE THREAD

**Issue by mackie100** [mackie100/OCClocalizations#8]
@btwise https://github.com/mackie100/OCClocalizations/blob/b90b998c55a861522b9f21402d3fa6eb4bd1731d/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/Localizable.strings#L213

https://github.com/mackie100/OCClocalizations/blob/b90b998c55a861522b9f21402d3fa6eb4bd1731d/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/Localizable.strings#L400

https://github.com/mackie100/OCClocalizations/blob/b90b998c55a861522b9f21402d3fa6eb4bd1731d/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/Localizable.strings#L403

https://github.com/mackie100/OCClocalizations/blob/b90b998c55a861522b9f21402d3fa6eb4bd1731d/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/MainMenu.strings#L350

https://github.com/mackie100/OCClocalizations/blob/b90b998c55a861522b9f21402d3fa6eb4bd1731d/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/MainMenu.strings#L395

https://github.com/mackie100/OCClocalizations/blob/b90b998c55a861522b9f21402d3fa6eb4bd1731d/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/MainMenu.strings#L404

**Comment by btwise** [comment]
Looks like we're going to have to modify some of the features!
Add A few suggestions:
1.The background and text of the TIPS section can be customized
2.The dwell time of the Tips is set to disappear as the mouse moves, not as a fixed time, because if the prompt is large enough, the mouse has to be moved again
3.In the Tips increases the identification url address function, convenient may jump to some related website study
4.Put some of the most common features of the Menu Bar, such as the mount partition, in the TOOLS added to the main interface, because many people are not used to looking at the menu bar

**Comment by mackie100** [comment]
Tooltips will be replaced by tips window

**Comment by btwise** [comment]
A form with buttons？Is it GonNa be a bad experience？Can you give me a little preview!

**Comment by btwise** [comment]
OC has updated a lot of options, OCC update it quickly!
